CREATE DATABASE IF NOT EXISTS yk_eggs CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE yk_eggs;

CREATE TABLE IF NOT EXISTS calculations (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    trays_purchased INT UNSIGNED NOT NULL,
    buying_price DECIMAL(12,2) NOT NULL DEFAULT 0,
    selling_price DECIMAL(12,2) NOT NULL DEFAULT 0,
    breakage_pct DECIMAL(6,2) NOT NULL DEFAULT 0,
    broken_trays DECIMAL(12,2) NOT NULL DEFAULT 0,
    sellable_trays DECIMAL(12,2) NOT NULL DEFAULT 0,
    transport DECIMAL(12,2) NOT NULL DEFAULT 0,
    loading DECIMAL(12,2) NOT NULL DEFAULT 0,
    other_expenses DECIMAL(12,2) NOT NULL DEFAULT 0,
    purchase_cost DECIMAL(14,2) NOT NULL DEFAULT 0,
    total_sales DECIMAL(14,2) NOT NULL DEFAULT 0,
    total_cost DECIMAL(14,2) NOT NULL DEFAULT 0,
    net_profit DECIMAL(14,2) NOT NULL DEFAULT 0,
    break_even_price DECIMAL(14,2) NOT NULL DEFAULT 0,
    profit_margin DECIMAL(8,2) NOT NULL DEFAULT 0,
    note VARCHAR(255) DEFAULT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);